[package]
name = "boa-hongg"
version = "0.1.0"
authors = ["Alexander Kj√§ll <alexander.kjall@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5"
Boa = "0.10.0"
